import {
  BarChart3,
  Calendar,
  CheckCircle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FileText,
  Folder,
  ShoppingCart,
  UserCircle,
  Users,
} from 'lucide-react';
import type { ActionItem } from './types';

export const demoQuickAccessItems: ActionItem[] = [
  {
    id: 'datos-personales',
    label: 'Datos personales',
    hint: 'Perfil del empleado',
    icon: <UserCircle className="h-6 w-6 text-white" />,
    gradient: 'from-blue-500 via-sky-500 to-indigo-500',
    href: '/datos',
  },
  {
    id: 'gestionar-empleados',
    label: 'Gestionar empleados',
    hint: 'Administrar equipo',
    icon: <Users className="h-6 w-6 text-white" />,
    gradient: 'from-indigo-500 via-violet-500 to-purple-500',
    role: 'manager',
    href: '/empleados',
  },
  {
    id: 'fichar',
    label: 'Fichar',
    hint: 'Control de horarios',
    icon: <Clock className="h-6 w-6 text-white" />,
    gradient: 'from-emerald-500 via-teal-500 to-cyan-500',
    href: '/fichaje',
  },
  {
    id: 'solicitudes',
    label: 'Solicitudes',
    hint: 'Gestionar peticiones',
    icon: <ClipboardList className="h-6 w-6 text-white" />,
    gradient: 'from-purple-500 via-fuchsia-500 to-pink-500',
    href: '/solicitudes',
  },
  {
    id: 'documentos',
    label: 'Documentos',
    hint: 'Nóminas y archivos',
    icon: <FileText className="h-6 w-6 text-white" />,
    gradient: 'from-orange-500 via-amber-500 to-yellow-500',
    href: '/documentos',
  },
  {
    id: 'documentos-empleados',
    label: 'Documentos empleados',
    hint: 'Archivos por empleado',
    icon: <Folder className="h-6 w-6 text-white" />,
    gradient: 'from-teal-500 via-cyan-500 to-sky-500',
    role: 'manager',
    href: '/documentos-empleados',
  },
  {
    id: 'cuadrantes',
    label: 'Cuadrantes',
    hint: 'Gestión de horarios',
    icon: <Calendar className="h-6 w-6 text-white" />,
    gradient: 'from-slate-500 via-gray-500 to-zinc-500',
    role: 'manager',
    href: '/cuadrantes',
  },
  {
    id: 'mi-horario',
    label: 'Mi horario',
    hint: 'Consulta tu cuadrante',
    icon: <Calendar className="h-6 w-6 text-white" />,
    gradient: 'from-sky-500 via-blue-500 to-indigo-500',
    href: '/cuadrantes-empleado',
  },
  {
    id: 'aprobaciones',
    label: 'Aprobaciones',
    hint: 'Aprobar solicitudes',
    icon: <CheckCircle className="h-6 w-6 text-white" />,
    gradient: 'from-yellow-500 via-amber-500 to-orange-500',
    role: 'manager',
    href: '/aprobaciones',
  },
  {
    id: 'pedidos',
    label: 'Pedidos',
    hint: 'Crear pedidos',
    icon: <ShoppingCart className="h-6 w-6 text-white" />,
    gradient: 'from-amber-500 via-orange-500 to-yellow-500',
    href: '/pedidos',
  },
  {
    id: 'estadisticas',
    label: 'Estadísticas',
    hint: 'Análisis y reportes',
    icon: <BarChart3 className="h-6 w-6 text-white" />,
    gradient: 'from-fuchsia-500 via-purple-500 to-cyan-500',
    role: 'manager',
    href: '/estadisticas',
  },
  {
    id: 'mis-inspecciones',
    label: 'Mis inspecciones',
    hint: 'Inspecciones asignadas',
    icon: <ClipboardCheck className="h-6 w-6 text-white" />,
    gradient: 'from-cyan-500 via-sky-500 to-blue-500',
    href: '/mis-inspecciones',
  },
];


